# Generated by Django 3.2.12 on 2022-02-16 19:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0159_auto_20220216_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycollection',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='account.user'),
            preserve_default=False,
        ),
    ]
